[package]
name = "basic_render"
version = "0.1.0"
edition = "2024"

[dependencies]
soyuz = { path = "../../" }
winit = "0.30.12"
wgpu = "27.0.1"
pollster = "0.4.0"
bytemuck = { version = "1.13", features = ["derive"] }
image = "0.25"
glam = "0.30"
